动态:
  时间问候: # 由于不同玩家时区不同，需要特殊处理。
    清晨:
      - 早上好~
      - おはよう！
      - 贵安~
      - "As the morning dew greets the coming dawn, so do I greet you, my dear friend.\n"
      - "在鲈鱼街角的第三根肋骨上向朝阳之子道声“早上好！”\n"
    上午:
      - 上午好
      - 上午好，让凯露来朵蜜你吧！
      - To make each day count.
      - 贵安~
    晚上:
      - 晚上好
      - 晚上好。愿我如星君如月，夜夜流光相皎洁。
      - 晚上好，来迎接月之法苏（凯露）吧！
      - 贵安~
    凌晨:
      - 有约不来过夜半，闲敲棋子落灯花。
      - 之子期宿来，孤琴候萝径。
      - 晚安~
      - 三天三夜！三更半夜！mc不停歇！！！！！
玩家:
  连接:
    新玩家连接广播:
      - 玩家<%= it.name %>正在连接服务器……这位是新朋友喵！
      - 灵动星球新成员<%= it.name %>正在着陆中……
    老玩家连接广播:
      - 玩家<%= it.name %>连接服务器
      - 玩家<%= it.name %>祈祷中……
      - 小伙伴<%= it.name %>来啦，正在连接……
      - 小伙伴<%= it.name %>抵达了灵动星球，正在着陆……
    新玩家连接欢迎语:
      - 你好，欢迎加入灵动MC，我们是一个有爱的大家庭！请按提示注册账号并登录吧~
    老玩家登录欢迎语:
      - 你好，欢迎来到灵动mc！
      - 开拓者，欢迎回家！
      - お帰りなさいませ！ご主人様！
      - 原神，启动！
      - 灵动MC欢迎你的归来。
      - 欢迎旅行者回到灵动大陆喵（雾
  登录:
    玩家登录广播:
      - 玩家<%= it.name %>已登录！
      - 玩家<%= it.name %>成功降临在灵动星球！
    玩家登录超时广播:
      - 玩家<%= it.name %>还在登录……是怎么回事呢OVO？
      - 玩家<%= it.name %>在等什么呢？两块钱买不了吃亏！两块钱买不了上当！快点登录呀！
  登出:
    玩家登出广播:
      - 玩家<%= it.name %>已下线，欢迎下次再来哦。
      - 玩家<%= it.name %>已下线，谢→谢→光↗临→！
      - 玩家<%= it.name %>已经驾驶飞船离开啦~
  进度:
    玩家达成进度:
      - 玩家<%= it.name %>达成进度“<%= it.advancement %>”。
      - 小伙伴<%= it.name %>刚刚达成进度“<%= it.advancement %>”。
    玩家达成目标:
      - 玩家<%= it.name %>实现了目标“<%= it.advancement %>”！厉害！
      - 小伙伴<%= it.name %>刚刚取得了目标“<%= it.advancement %>”！太强了！
    玩家达成挑战:
      - 小伙伴<%= it.name %>刚刚成功完成了挑战“<%= it.advancement %>”，展现了自己强大的实力！大家一起恭喜他呀~
消息:
  转发MC消息到QQ:
    - "<<%= it.name %>> <%= it.message %>"
  转发QQ消息到MC:
    - "[来自群聊] <<%= it.name %>> <%= it.message %>"
  转发到QQ被拦截广播: # reason取值： '不合规' '疑似违规'
    - "玩家<%= it.name %>的消息<%= it.reason %>，被拦截。蒸膜，你不扶器吗？"
    - "<%= it.name %>刚刚发送的消息<%= it.reason %>，未同步到QQ。希望加强学习，认真反省。"
    - "玩家<%= it.name %>的消息因为加入了<%= it.reason %>的内容而过于美味，被嗷呜一口吞掉了喵~"
状态:
  在线玩家:
    - |
      灵动星球在线玩家数: <%= it.length %> 人：
      <%= it.join('\n') %>
  无人在线:
    - 当前服务器内没有玩家哦~
    - 服务器里没有玩家，小伙伴都休息去啦。
    - 服务器里没人啦！呜呜呜……
    - 让我看看……咦！！服务器没人在线！大家快来登录喵~
    - 服务器里没人啦，快点登录哟，仁家空虚寂寞喵呜……
    - zzZ... 服务器没人，都要闲出草来了QWQ。
    - 服务器里一个人都没有，可怜……
    - 对不起，我知道你很想找小伙伴一起玩，可是现在服务器里确实没有人欸……
    - RUA！服务器居然没人在线！
    - 啊嘞嘞，好奇怪哦。服务器里怎么一个人都没有呢( ﾟдﾟ) ？
    - 服务器没人！大家快来建设灵动MC呀，快呀快呀 (◉ω◉)！
    - 服务器里一个人都没有，人家空虚寂寞，实在忍不了了！快来上线！（震声
    - 虽然现在服务器里没有人，不过建设伟大的灵动MC是大家不可推卸的责任！加油！
    - 天啊，服务器里一个人都没有，只有我一个人在这里玩又有什么意思呢？
    - 服务器里根本没有人！全是僵尸、小白、苦力怕！呜啊，好可怕！
    - 服务器里没人啦，别问服务器里有没有人在线，你上线就有人在了！
    - 服务器里没人。不过这条消息是彩蛋，能触发的这条消息，你运气也不错。
    - 服务器里空荡荡的，一个小伙伴都没有~
    - 没人没人，别问啦！真是的，就知道问问问，也不来上线陪陪我呜呜呜
    - 喝啊！大河向东流，灵动MC的服务器里的玩家有没有……没有没有一个没有！
    - 服务器没人，不要再问了。
    - 没人哦，再问，再问就把你吃掉owo~
    - 鲁迅先生说过，服里空荡荡，玩家在人间。
    - 倒是终究被哥哥嫌弃了，不像其他妹妹生的俊俏，竟一个人都不见来。
    - 哥哥姐姐们怕不是又被哪位小宝贝绊住了，竟都如此不理人了(・へ・)。
    - 终究是熬到了下班时间也等不到宝贝的一句消息，怕不是今晚宝贝又要加班了？留妹妹独自一人暗自伤神。
    - 鲁酒不可醉，齐歌空复情。思君若汶水，浩荡寄南征。
    - 春草今又绿，王孙归不归？
    - 人归落雁后，思发在花前。
    - 俯首叫父老，旷野无人声。
    - 杳杳寒山道，落落冷涧滨。啾啾常有鸟，寂寂更无人。
    - 服务器里一个小伙伴都没有哟，但是你来关心我了，好感动，啾咪~（来自neboer的香吻
管理:
  帮助:
    - |
      #mc 查询当前在线人数
      #version 查询机器人版本
      #help 查看此帮助信息
      #neboer ？？？
  彩蛋:
    触发Neboer:
      - HOW! DARE! YOU!!!!!
      - Neboer是谁真不熟
      - Neboer在兰德索尔旅游
      - Neboer在提瓦特旅游
      - Neboer在嚎哭深渊旅游
      - Neboer在打每人一小块地
      - 关注万年榕树喵，关注万年榕树谢谢喵！
      - 你好，请问找Neboer有什么事情吗？
Negactivity:
  作弊封禁:
    - "玩家<%= it.name %>因<%= it.reason %>被封禁至<%= it.time %>，好孩子不要学习哦？"