动态:
  时间问候: # 由于不同玩家时区不同，需要特殊处理。
    清晨:
      - 早上好~
    上午:
      - 上午好
玩家:
  连接:
    新玩家连接广播:
      - 新朋友<%= it.name %>正在连接服务器……
      - 灵动星球迎来了新成员<%= it.name %>！正在着陆中……
    老玩家连接广播:
      - 玩家<%= it.name %>连接服务器
      - 小伙伴<%= it.name %>来啦，正在连接……
      - 小伙伴<%= it.name %>抵达了灵动星球，正在着陆……
    新玩家连接欢迎语:
      - 你好，欢迎加入灵动MC，我们是一个有爱的大家庭！请按提示注册账号吧~
    老玩家登录欢迎语:
      - 你好，欢迎来到mc！
      - 开拓者，欢迎回家！
  登录:
    玩家登录广播:
      - 玩家<%= it.name %>已登录！
      - 玩家<%= it.name %>成功降临在灵动星球！
    玩家登录超时广播:
      - 玩家<%= it.name %>还在登录……是怎么回事呢？
      - 玩家<%= it.name %>在等什么呢？快点登录呀！
  登出:
    玩家登出广播:
      - 玩家<%= it.name %>已下线，欢迎再来哦。
      - 玩家<%= it.name %>已经驾驶飞船离开啦~
消息:
  转发MC消息到QQ:
    - "<<%= it.name %>> <%= it.message %>"
  转发QQ消息到MC:
    - "[来自群聊] <<%= it.name %>> <%= it.message %>"
  转发到QQ被拦截广播:
    - "玩家<%= it.name %>的消息未通过审核，被拦截。拦截原因：<%= it.reason %>"
    - "<%= it.name %>刚刚发送的消息可能违规，未同步到QQ。原因：<%= it.reason %>"
状态:
  在线玩家:
    - |
      服务器人数: <%= it.length %> 人：
      <%= it.join('\n') %>
  无人在线:
    - 当前服务器内没有玩家哦~
    - 服务器里没有玩家，小伙伴都休息去啦。
管理:
  帮助:
    - |
      #mc 查询当前在线人数
      #version 查询机器人版本
      #help 查看此帮助信息